package forms;

import enums.InstallmentStatus;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Installment;
import model.ProductSold;
import model.Sale;
import utils.Mask;

public class ModalViewCompletedSale extends javax.swing.JDialog {

    private Sale selectedSale;
    private List<ProductSold> products;

    public ModalViewCompletedSale(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompletedSale = new javax.swing.JTable();
        fieldCurrentInstallmentValue1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JLabel();
        fieldCurrentInstallmentValue2 = new javax.swing.JLabel();
        fieldCurrentInstallmentValue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldCurrentInstallment = new javax.swing.JLabel();
        fieldDueDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelClientName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENDA FINALIZADA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(14, 171, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENDA FINALIZADA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        tableCompletedSale.setRowHeight(25);
        tableCompletedSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCompletedSale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCompletedSale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCompletedSale.setShowHorizontalLines(true);
        tableCompletedSale.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCompletedSale);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        centerRenderer.setVerticalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tableCompletedSale.getColumnCount(); i++) {
            tableCompletedSale.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        if (tableCompletedSale.getColumnModel().getColumnCount() > 0) {
            tableCompletedSale.getColumnModel().getColumn(0).setMinWidth(50);
            tableCompletedSale.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableCompletedSale.getColumnModel().getColumn(0).setMaxWidth(50);
            tableCompletedSale.getColumnModel().getColumn(1).setResizable(false);
            tableCompletedSale.getColumnModel().getColumn(2).setMinWidth(100);
            tableCompletedSale.getColumnModel().getColumn(2).setPreferredWidth(100);
            tableCompletedSale.getColumnModel().getColumn(2).setMaxWidth(100);
            tableCompletedSale.getColumnModel().getColumn(3).setMinWidth(120);
            tableCompletedSale.getColumnModel().getColumn(3).setPreferredWidth(120);
            tableCompletedSale.getColumnModel().getColumn(3).setMaxWidth(120);
        }

        fieldCurrentInstallmentValue1.setBackground(new java.awt.Color(255, 255, 255));
        fieldCurrentInstallmentValue1.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        fieldCurrentInstallmentValue1.setForeground(new java.awt.Color(51, 51, 51));
        fieldCurrentInstallmentValue1.setText("R$ ");
        fieldCurrentInstallmentValue1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Valor:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Total:");

        fieldTotal.setBackground(new java.awt.Color(255, 255, 255));
        fieldTotal.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        fieldTotal.setForeground(new java.awt.Color(51, 51, 51));
        fieldTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fieldCurrentInstallmentValue2.setBackground(new java.awt.Color(255, 255, 255));
        fieldCurrentInstallmentValue2.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        fieldCurrentInstallmentValue2.setForeground(new java.awt.Color(51, 51, 51));
        fieldCurrentInstallmentValue2.setText("R$ ");
        fieldCurrentInstallmentValue2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fieldCurrentInstallmentValue.setBackground(new java.awt.Color(255, 255, 255));
        fieldCurrentInstallmentValue.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        fieldCurrentInstallmentValue.setForeground(new java.awt.Color(51, 51, 51));
        fieldCurrentInstallmentValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Vencimento:");

        fieldCurrentInstallment.setBackground(new java.awt.Color(255, 255, 255));
        fieldCurrentInstallment.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        fieldCurrentInstallment.setForeground(new java.awt.Color(51, 51, 51));
        fieldCurrentInstallment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fieldDueDate.setBackground(new java.awt.Color(255, 255, 255));
        fieldDueDate.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        fieldDueDate.setForeground(new java.awt.Color(51, 51, 51));
        fieldDueDate.setText(" ");
        fieldDueDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Parcelas:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Cliente:");

        labelClientName.setBackground(new java.awt.Color(255, 255, 255));
        labelClientName.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        labelClientName.setForeground(new java.awt.Color(51, 51, 51));
        labelClientName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCurrentInstallmentValue1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCurrentInstallmentValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCurrentInstallment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCurrentInstallmentValue2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCurrentInstallmentValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldCurrentInstallmentValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCurrentInstallment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldCurrentInstallmentValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel model = (DefaultTableModel) tableCompletedSale.getModel();
        selectedSale = SummariesDialog.getSelectedSale();
        products = selectedSale.getProductsSold();

        for (ProductSold product : products) {
            Object[] row = {
                product.getId(),
                product.getName(),
                product.getQuantity(),
                product.getTotal()
            };
            model.addRow(row);
        }

        labelClientName.setText(selectedSale.getClientName());

        Installment nextInstallment = selectedSale.getInstallments().stream()
                .filter(i -> i.getStatus() == InstallmentStatus.PENDING
                || i.getStatus() == InstallmentStatus.OVERDUE
                || i.getStatus() == InstallmentStatus.PARTIALLY_PAID)
                .findFirst()
                .orElse(null);

        if (nextInstallment != null) {
            BigDecimal outstanding = nextInstallment.getOutstandingBalance();
            fieldCurrentInstallmentValue.setText(String.format("R$ %.2f", outstanding));
            fieldDueDate.setText(Mask.sdf.format(java.sql.Date.valueOf(nextInstallment.getDueDate())));

            int index = selectedSale.getInstallments().indexOf(nextInstallment) + 1;
            int total = selectedSale.getInstallments().size();
            fieldCurrentInstallment.setText(String.format("%d de %d", index, total));
        } else {
            fieldCurrentInstallmentValue.setText("Quitado");
            fieldCurrentInstallment.setText("-");
            fieldDueDate.setText("-");
        }

        fieldTotal.setText(String.format("R$ %.2f", selectedSale.getTotalValue()));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalViewCompletedSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalViewCompletedSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalViewCompletedSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalViewCompletedSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModalViewCompletedSale dialog = new ModalViewCompletedSale(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fieldCurrentInstallment;
    private javax.swing.JLabel fieldCurrentInstallmentValue;
    private javax.swing.JLabel fieldCurrentInstallmentValue1;
    private javax.swing.JLabel fieldCurrentInstallmentValue2;
    private javax.swing.JLabel fieldDueDate;
    private javax.swing.JLabel fieldTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelClientName;
    private javax.swing.JTable tableCompletedSale;
    // End of variables declaration//GEN-END:variables
}
