package forms;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import enums.DiscountType;
import java.io.IOException;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import model.Client;
import model.Item;
import utils.Json;
import utils.Mask;
import utils.Sale;

/**
 *
 * @author xnilm
 */
public class SaleDialog extends javax.swing.JDialog {

    private List<Item> productsList;
    private List<Client> clientsList;
    private String slc = "Selecione";
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    //
    public SaleDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboProduct = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        spinnerAmount = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        comboClient = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboDiscount = new javax.swing.JComboBox<>();
        labelDiscountValue = new javax.swing.JLabel();
        spinnerDiscountValue = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        dateBillingDate = new com.toedter.calendar.JDateChooser();
        checkInstallment = new javax.swing.JCheckBox();
        spinnerInstallment = new javax.swing.JSpinner();
        labelInstallment = new javax.swing.JLabel();
        buttonProceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REALIZAR VENDA");
        setPreferredSize(new java.awt.Dimension(560, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(14, 171, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENDER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Produto:");

        comboProduct.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        comboProduct.setForeground(new java.awt.Color(51, 51, 51));
        comboProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Quantidade:");

        spinnerAmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinnerAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAmountStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Cliente:");

        comboClient.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        comboClient.setForeground(new java.awt.Color(51, 51, 51));
        comboClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Desconto:");

        comboDiscount.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        comboDiscount.setForeground(new java.awt.Color(51, 51, 51));
        comboDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiscountActionPerformed(evt);
            }
        });

        labelDiscountValue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        labelDiscountValue.setForeground(new java.awt.Color(51, 51, 51));
        labelDiscountValue.setText("Valor:");
        labelDiscountValue.setAutoscrolls(true);
        labelDiscountValue.setEnabled(false);

        spinnerDiscountValue.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        spinnerDiscountValue.setAutoscrolls(true);
        spinnerDiscountValue.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Data de cobrança:");

        checkInstallment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        checkInstallment.setForeground(new java.awt.Color(51, 51, 51));
        checkInstallment.setText("Parcelamento");
        checkInstallment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInstallmentActionPerformed(evt);
            }
        });

        spinnerInstallment.setEnabled(false);

        labelInstallment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelInstallment.setForeground(new java.awt.Color(51, 51, 51));
        labelInstallment.setText("N°");
        labelInstallment.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(comboDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelDiscountValue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comboProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(checkInstallment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelInstallment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerInstallment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateBillingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(214, 214, 214))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboClient, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinnerDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateBillingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInstallment)
                    .addComponent(spinnerInstallment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInstallment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonProceed.setBackground(new java.awt.Color(0, 128, 163));
        buttonProceed.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        buttonProceed.setForeground(new java.awt.Color(255, 255, 255));
        buttonProceed.setText("PROSSEGUIR");
        buttonProceed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(buttonProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(buttonProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClientActionPerformed

    private void comboDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiscountActionPerformed
        Mask.refreshDiscountSpinner(comboDiscount, comboProduct, spinnerAmount,
                spinnerDiscountValue, labelDiscountValue, productsList);
    }//GEN-LAST:event_comboDiscountActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ObjectMapper mapper = new ObjectMapper();
        mapper.enable(SerializationFeature.INDENT_OUTPUT);

        DefaultComboBoxModel<String> modelP = new DefaultComboBoxModel<>();
        modelP.addElement(slc);

        DefaultComboBoxModel<String> modelC = new DefaultComboBoxModel<>();
        modelC.addElement(slc);

        try {
            String contentP = Files.exists(Json.getProductsFileLocation())
                    ? Files.readString(Json.getProductsFileLocation())
                    : "[]";

            String contentC = Files.exists(Json.getClientsFileLocation())
                    ? Files.readString(Json.getClientsFileLocation())
                    : "[]";

            productsList = mapper.readValue(contentP, new TypeReference<>() {
            });
            clientsList = mapper.readValue(contentC, new TypeReference<>() {
            });

            for (Item item : productsList) {
                modelP.addElement(String.format("%05d - %s", item.getId(), item.getName()));
            }

            for (Client client : clientsList) {
                modelC.addElement(String.format("%05d - %s", client.getId(), client.getName()));
            }

            comboProduct.setModel(modelP);
            comboClient.setModel(modelC);

            comboProduct.addActionListener(e -> {
                if (comboProduct.getSelectedIndex() > 0) {
                    DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) comboProduct.getModel();
                    if (model.getIndexOf(slc) != -1) {
                        model.removeElement(slc);
                    }
                }
            });

            comboClient.addActionListener(e -> {
                if (comboClient.getSelectedIndex() > 0) {
                    DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) comboClient.getModel();
                    if (model.getIndexOf(slc) != -1) {
                        model.removeElement(slc);
                    }
                }
            });

        } catch (IOException ex) {
            Logger.getLogger(SaleDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultComboBoxModel cbm = new DefaultComboBoxModel<>(DiscountType.values());
        comboDiscount.setModel(cbm);
    }//GEN-LAST:event_formWindowOpened

    private void comboProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductActionPerformed
        int selected = comboProduct.getSelectedIndex();

        SpinnerNumberModel model = new SpinnerNumberModel(1, 1, productsList.get(selected).getAmount(), 1);
        spinnerAmount.setModel(model);

        Mask.refreshDiscountSpinner(comboDiscount, comboProduct, spinnerAmount, spinnerDiscountValue, labelDiscountValue, productsList);
    }//GEN-LAST:event_comboProductActionPerformed

    private void buttonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProceedActionPerformed
        if (comboClient.getSelectedItem().equals(slc) || comboProduct.getSelectedItem().equals(slc)) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Item selectedProduct = productsList.get(comboProduct.getSelectedIndex());
        Client selectedClient = clientsList.get(comboClient.getSelectedIndex());

        int amount = ((Number) spinnerAmount.getValue()).intValue();
        double grossValue = amount * selectedProduct.getPrice();

        if (grossValue > selectedProduct.getTotal()) {
            JOptionPane.showMessageDialog(null, "Erro na venda! (Valor bruto maior que o estoque)", "ERRO!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double netValue;
        double discountValue = ((Number) spinnerDiscountValue.getValue()).doubleValue();

        double absoluteDiscount = 0;
        double percentageDiscount = 0;

        if (comboDiscount.getSelectedIndex() == 1) {
            percentageDiscount = discountValue;
            absoluteDiscount = grossValue * (percentageDiscount / 100.0);
            netValue = grossValue - absoluteDiscount;
        } else {
            absoluteDiscount = discountValue;
            percentageDiscount = (absoluteDiscount / grossValue) * 100.0;
            netValue = grossValue - absoluteDiscount;
        }

        if (dateBillingDate == null) {
            JOptionPane.showMessageDialog(null, "Escolha uma data de cobrança!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Date billingDate = dateBillingDate.getDate();
        String formatedBillingDate = sdf.format(billingDate);

        System.out.println(formatedBillingDate);

        int numberOfInstallments = ((Number) spinnerInstallment.getValue()).intValue();
        
        double installmentValue = netValue / numberOfInstallments;

        List<Date> allBillingDates = Sale.allBillingDates(billingDate, numberOfInstallments);

        String lastBillingDate = sdf.format(allBillingDates.getLast());

        if (!Sale.finishSale(selectedClient.getName(), selectedClient.getCpf(), selectedProduct.getPrice(), grossValue,
                amount, absoluteDiscount, percentageDiscount, netValue, installmentValue, selectedProduct, selectedClient, formatedBillingDate,
                numberOfInstallments, lastBillingDate)) {
            JOptionPane.showMessageDialog(null, "Operação cancelada!", "CANCELAMENTO", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //logica para atualizar os valores no json
    }//GEN-LAST:event_buttonProceedActionPerformed

    private void spinnerAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAmountStateChanged
        Mask.refreshDiscountSpinner(comboDiscount, comboProduct, spinnerAmount, spinnerDiscountValue, labelDiscountValue, productsList);
    }//GEN-LAST:event_spinnerAmountStateChanged

    private void checkInstallmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInstallmentActionPerformed
        SpinnerNumberModel modelFalse = new SpinnerNumberModel(0, 0, 0, 0);
        SpinnerNumberModel modelTrue = new SpinnerNumberModel(2, 2, 100, 1);

        if (checkInstallment.isSelected()) {
            spinnerInstallment.setModel(modelTrue);
            spinnerInstallment.setEnabled(true);
            labelInstallment.setEnabled(true);
        } else {
            spinnerInstallment.setModel(modelFalse);
            spinnerInstallment.setEnabled(false);
            labelInstallment.setEnabled(false);
        }
    }//GEN-LAST:event_checkInstallmentActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaleDialog dialog = new SaleDialog(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProceed;
    private javax.swing.JCheckBox checkInstallment;
    private javax.swing.JComboBox<String> comboClient;
    private javax.swing.JComboBox<String> comboDiscount;
    private javax.swing.JComboBox<String> comboProduct;
    private com.toedter.calendar.JDateChooser dateBillingDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDiscountValue;
    private javax.swing.JLabel labelInstallment;
    private javax.swing.JSpinner spinnerAmount;
    private javax.swing.JSpinner spinnerDiscountValue;
    private javax.swing.JSpinner spinnerInstallment;
    // End of variables declaration//GEN-END:variables
}
